### PR TITLE
FIX: Cursor and Statusline Jitters on Start-Up, Saving, Scroll etc

### PR DESCRIPTION
**Pull request by Pheon-Dev**
Temporary Fix: Skip Health Check to Prevent The Jitters on Save, Start-Up, Linting, Formatting  etc

### CODE REVIEW

**Comment by folke** [comment]
Can you let me know what caused problems? I don't see how the health checks could cause any jitters anywhere. They are ran every second, but do close to nothing.

**Comment by folke** [comment]
Health checks aren't even running right now, dus to a change I made a couple of days ago.
https://github.com/folke/noice.nvim/blob/26266b0a4eec836e259544e28973d9d22f09b5bb/lua/noice/health.lua#L113

`require("noice")._running` is always `nil`. (fixed it locally already)

**Comment by Pheon-Dev** [comment]
Well now I'm not so sure what could be causing the problem, but that fix works for me, I'll try and share a screen recording of the jitters

**Comment by Pheon-Dev** [comment]
Well now I'm not so sure what could be causing the problem, but that fix works for me, I'll try and share a screen recording of the jitters

**Comment by folke** [comment]
That's weird indeed. Do let me know if you find anything. Even better if you can reproduce it with https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

Side question. What do you use for formatting Markdown? :) Is that deno?

**Comment by folke** [comment]
There was a mmeory leak with lsp_progress that could have caused a slow down https://github.com/folke/noice.nvim/issues/89

**Comment by Pheon-Dev** [comment]
I tried to reproduce the problem but couldn't, which means it's most certainly one of the plugins

**Comment by Pheon-Dev** [comment]
Just found out the root of the problem is with the notify plugin, the statusline blinks repeatedly whenever there's a notification. I had it invoked twice inside packer.
```
  use({
      "rcarriga/nvim-notify",
    })
  ...
  ...
  use({
      "folke/noice.nvim",
      event = "VimEnter",
      config = "require('config.noice')",
      requires = {
        "MunifTanjim/nui.nvim",
        "rcarriga/nvim-notify",
      },
   })
```
Once I removed the first instance and recompiled my plugins, everything is now all noice and sweet.

Sidenote:
Didn't quite understand which markdown you were referring to but I use prettier for now whenever `lua vim.lsp.buf.formatting()` doesn't seem to quite cut it.
Configuring [remark](https://remark.js.org/) to work with [ale](https://github.com/dense-analysis/ale) can help with Markdown linting, formatting
and fixing.
 
Thanks for the great help and for tokyonight, which-key neodev and many other awesome plugins, keep'em coming

**Pull request closed without merging**
