### PR TITLE
fix(markdown): increase regex pattern specificity

### LINKED ISSUE #902: bug: Invalid character in group name
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Debian 12

### Describe the bug

<details>

<summary> Error </summary>

```
Error detected while processing nvim_exec2():
Error executing vim.schedule lua callback: .../site/pack/deps/opt/noice.nvim/lua/noice/text/syntax.lua:9: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim(syntax):E5248: Invalid character in group name
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	.../site/pack/deps/opt/noice.nvim/lua/noice/text/syntax.lua:18: in function <.../site/pack/deps/opt/noice.nvim/lua/noice/text/syntax.lua:9>
	[C]: in function 'nvim_buf_call'
	.../site/pack/deps/opt/noice.nvim/lua/noice/text/syntax.lua:9: in function 'highlight'
	...im/site/pack/deps/opt/noice.nvim/lua/noice/text/init.lua:70: in function 'highlight'
	...e/nvim/site/pack/deps/opt/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...e/nvim/site/pack/deps/opt/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...m/site/pack/deps/opt/noice.nvim/lua/noice/text/block.lua:98: in function 'render'
	...site/pack/deps/opt/noice.nvim/lua/noice/lsp/override.lua:52: in function 'stylize_markdown'
	...m/site/pack/deps/opt/nvim-cmp/lua/cmp/view/docs_view.lua:64: in function 'open'
	.../share/nvim/site/pack/deps/opt/nvim-cmp/lua/cmp/view.lua:292: in function 'callback'
	...nvim/site/pack/deps/opt/nvim-cmp/lua/cmp/utils/async.lua:138: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'nvim_buf_call'
	.../site/pack/deps/opt/noice.nvim/lua/noice/text/syntax.lua:9: in function 'highlight'
	...im/site/pack/deps/opt/noice.nvim/lua/noice/text/init.lua:70: in function 'highlight'
	...e/nvim/site/pack/deps/opt/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...e/nvim/site/pack/deps/opt/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...m/site/pack/deps/opt/noice.nvim/lua/noice/text/block.lua:98: in function 'render'
	...site/pack/deps/opt/noice.nvim/lua/noice/lsp/override.lua:52: in function 'stylize_markdown'
	...m/site/pack/deps/opt/nvim-cmp/lua/cmp/view/docs_view.lua:64: in function 'open'
	.../share/nvim/site/pack/deps/opt/nvim-cmp/lua/cmp/view.lua:292: in function 'callback'
	...nvim/site/pack/deps/opt/nvim-cmp/lua/cmp/utils/async.lua:138: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
E21: Cannot make changes, 'modifiable' is off
```

</details>

Under certain circumstances completion produces the error above.

Apparently, the value of `lang` variable in `M.highlight()` function becomes `{toml}` for some reason.

I'm able to reliably reproduce the error with these snippets of code:

<details>

<summary> Code </summary>

**Cargo.toml**

```toml
[package]
name = "tom"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
```

**main.rs**

```rust
use convert_case;
fn main() {
    println!("Hello, world!");
}
```

</details> 

### Steps To Reproduce

1. Install 'rust-analyzer'
2. `cargo new tom`
3. Set the contents of `Cargo.toml` as above
4. Set the contets of `main.rs` as above
5. Wait for 'rust-analyzer' to load
6. Put the cursor on `convert_case` and press  `K`
7. Observe the error

### Expected Behavior

No error

### Repro

```lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

require('lazy.minit').repro({
  spec = {
    { 'MunifTanjim/nui.nvim' },
    { 'folke/noice.nvim', opts = {} },
    -- add any other plugins here
    { 'neovim/nvim-lspconfig' },
  },
})

require('lspconfig').rust_analyzer.setup({})
```

### PR DESCRIPTION
**Pull request by lostl1ght**
Fixes #902

### CODE REVIEW

**Comment by folke** [comment]
Sorry, but that's just not a valid code-block language.
I'm not going to add bug fixes for LSPs in Noice....

**Comment by lostl1ght** [comment]
Well, default hover is not crashing with the same code block:
image

IMO 'noice' should match that behavior.

**Comment by folke** [comment]
I'm fine with gracefully handling these types of errors, but not to fix bugs in a certain LSP.
So feel free to update the PR to do just that

**Comment by lostl1ght** [comment]
What do you mean by handling this error gracefully? Should noice send an error instead of trying to render a hover message if it has invalid markdown or do something else?

Also, apparently it is not a rust-analyzer error but an error in that library's documentation 😅

**Pull request closed without merging**
