### PR TITLE
Configurable cmdline and messages

### LINKED ISSUE #43: Cannot disable History/message/notify part
**Describe the bug**

I'm would love to just use the cmdline popup by itself, but I can't figure out how to disable the notify component. 

**Which version of Neovim are you using?**
Gui? Nightly? Version?
0.8
**To Reproduce**
Enable noice, set history, notify to { enabled = false}

**Expected Behavior**
messages to work as normal vim.

**Screenshots**
image

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Log comes here
</pre>
</details>

### PR DESCRIPTION
**Pull request by Shougo**
Fix #43

### CODE REVIEW

**Review by folke — COMMENTED** [review]
Hi @Shougo, thank you for the PR!

One thing to be aware of is that enabling ext_messages, always enables ext_cmdline in ui_attach. That's a current limitation of the api. There are plans to change this, but not sure if it will be ready for 0.9

So maybe add a note about this in the config/readme for cmdline.enabled?

**Comment by p00f** [comment]
I'd like `:messages` to use noice's actual buffer, just not use nvim-notify for messages. Is that possible?

**Comment by Shougo** [comment]
> One thing to be aware of is that enabling ext_messages, always enables ext_cmdline in ui_attach. That's a current limitation of the api. There are plans to change this, but not sure if it will be ready for 0.9

OK.

**Comment by p00f** [comment]
image

**Comment by Shougo** [comment]
> I'd like :messages to use noice's actual buffer, just not use nvim-notify for messages. Is that possible?

It is possible.  But the implementation seems hard...

**Comment by Shougo** [comment]
I have added backend config.

**Comment by Shougo** [comment]
The messages UI is too hard for me.

**Comment by Shougo** [comment]
I have tested to implement it, but failed.

**Comment by folke** [comment]
I'll have a look when I'm home. Instead of adding a new option, it's probably better to override config.views.notify. just set backend there to split instead of notify.

I'll add a config recipe to the wiki for this.

**Comment by p00f** [comment]
I meant `:messages` should open a split like it does and vim.notify should be the default one (i.e `echo`)

**Comment by p00f** [comment]
(Sorry, should I take this to a new issue?)

**Comment by folke** [comment]
@Shougo I've cherry-picked the first two commits, but didn't merge the last one for changing the backend. Will see for a better way to do this. I also need to make some changes first so that there's only one `split` view instance to make this work.

Closing this for now, but as I said, the config of cmdline and messages is merged :)

**Comment by Shougo** [comment]
OK.

**Pull request closed without merging**
